package render

import (
	_ "embed"
)

// github-markdown-css v5.9.0 — https://github.com/sindresorhus/github-markdown-css
//
//go:embed assets/github-markdown.css
var githubMarkdownCSS []byte

// Chroma "github" theme CSS generated by github.com/alecthomas/chroma v2.26.0
//
//go:embed assets/highlight-github.css
var highlightGithubCSS []byte

//go:embed assets/dollop-light.svg
var dollopLightSVG []byte

//go:embed assets/dollop-dark.svg
var dollopDarkSVG []byte

//go:embed assets/dollop-favicon.svg
var dollopFaviconSVG []byte

// SharedAsset is a file that should be uploaded at the prefix root with
// cache headers, separate from the per-file relPaths list.
type SharedAsset struct {
	Name        string
	ContentType string
	Content     []byte
}
